### ISSUE TITLE
Error: The option 'onComplete' is not recognised

### ISSUE THREAD

**Issue by eamodio** [ramirezcgn/fantasticon-webpack-plugin#1]
When trying to pass the `onComplete` callback in the `config` option it errors out with:

```
Error: The option 'onComplete' is not recognised
```

I'm trying to use the `config` options, because if I add it to my `.fantasticonrc.js` then running fantasticon directly won't work.

**Comment by eamodio** [comment]
I think it would be nice if the `runOnComplete` was just replaced directly with a `onComplete` callback.

This becomes extra important because https://github.com/tancredi/fantasticon can't accept an `onComplete` option in its configuration, so if you want to use both the command line and this webpack plugin you can't share the same `.fantasticon.js` config

**Comment by ramirezcgn** [comment]
Hi, I made in that way because I have different webpack config files and in some I need to run the "onComplete" callback, but in others not, I can just add that option to the plugin so you can run your own on complete in the webpack config.

Regards
