### ISSUE TITLE
Error after updating to v0.0.6

### ISSUE THREAD

**Issue by ReindDooyeweerd** [ramirezcgn/fantasticon-webpack-plugin#2]
Just updated to v0.0.6 but the plugin throws an error when building,

`Error: schema is invalid: data/properties/onComplete/type must be equal to one of the allowed values, data/properties/onComplete/type must be array, data/properties/onComplete/type must match a schema in anyOf
    at Ajv.validateSchema`

**Comment by ramirezcgn** [comment]
Hi, sorry, I temporarily fixed it in version 0.7 until I have the final fix.
